scalaStewardArgs:
  - --workspace
  - /var/scala-steward/workspace
  - --repos-file
  - /opt/scala-steward/repos.md
  - --vcs-api-host
  - https://api.github.com
  - --git-ask-pass
  - /opt/scala-steward/password.sh
  - --scalafix-migrations
  - /opt/scala-steward/scalafix.conf
  - --do-not-fork

additionalScalaStewardArgs:
  - --git-author-email
  - gh_tt01_u01@currencycloud.com
  - --vcs-login
  - gh_tt01_u01@currencycloud.com

additionalScalaStewardEnvs: {}
repos:
  - ccycloud-org-sandbox/akka
scalafixConfig: |
  disableDefaults = false
  migrations = []

gitSecret: ""
existingGitSecretName: stewardsecret

image:
  tag: latest
  repository: fthomas/scala-steward
  pullPolicy: IfNotPresent

schedule: "0 7 * * *"
concurrencyPolicy: "Forbid"

imagePullSecrets: [] 
nameOverride: ""
fullnameOverride: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

persistence:
  enabled: true
  className: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 5Gi
